from src_wikibase.fct_add_entities import get_entity_id_by_label, get_property_id_by_label, wikibase_api_url

wikibase_properties_id = {"instance of": get_property_id_by_label("instance of", wikibase_api_url),
                    "reference URL": get_property_id_by_label("reference URL", wikibase_api_url),
                    "start time": get_property_id_by_label("start time", wikibase_api_url),
                    "end time": get_property_id_by_label("end time", wikibase_api_url),
                    "occupation title": get_property_id_by_label("occupation title", wikibase_api_url),
                    "educated at": get_property_id_by_label("educated at", wikibase_api_url),
                    "employer": get_property_id_by_label("employer", wikibase_api_url),
                    "work location": get_property_id_by_label("work location", wikibase_api_url),
                    "award received": get_property_id_by_label("award received", wikibase_api_url),
                    "point in time": get_property_id_by_label("point in time", wikibase_api_url),
                    "exact match": get_property_id_by_label("exact match", wikibase_api_url),
                    "date of birth": get_property_id_by_label("date of birth", wikibase_api_url),
                    "place of birth": get_property_id_by_label("place of birth", wikibase_api_url),
                    "date of death": get_property_id_by_label("date of death", wikibase_api_url),
                    "country of citizenship": get_property_id_by_label("country of citizenship", wikibase_api_url),
                    "occupation": get_property_id_by_label("occupation", wikibase_api_url),
                    "sex or gender": get_property_id_by_label("sex or gender", wikibase_api_url),
                    "official website": get_property_id_by_label("official website", wikibase_api_url),
                    "perfumes": get_property_id_by_label("perfumes", wikibase_api_url),
                    "who wears it": get_property_id_by_label("who wears it", wikibase_api_url),
                    "inception": get_property_id_by_label("inception", wikibase_api_url),
                    "headquarters location": get_property_id_by_label("headquarters location", wikibase_api_url),
                    "parent organization": get_property_id_by_label("parent organization", wikibase_api_url),
                    "founded by": get_property_id_by_label("founded by", wikibase_api_url),
                    "owned by": get_property_id_by_label("owned by", wikibase_api_url),
                    "industry": get_property_id_by_label("industry", wikibase_api_url),
                    "country": get_property_id_by_label("country", wikibase_api_url),
                    "total revenue": get_property_id_by_label("total revenue", wikibase_api_url),
                    "designer employed": get_property_id_by_label("designer employed", wikibase_api_url),
                    "country of origin": get_property_id_by_label("country of origin", wikibase_api_url),
                    "fashion collection": get_property_id_by_label("fashion collection", wikibase_api_url),
                    "fashion season": get_property_id_by_label("fashion season", wikibase_api_url),
                    "fashion show location": get_property_id_by_label("fashion show location", wikibase_api_url),
                    "description of fashion collection": get_property_id_by_label("description of fashion collection", wikibase_api_url),
                    "image of fashion collection": get_property_id_by_label("image of fashion collection", wikibase_api_url),
                    "editor of fashion collection description": get_property_id_by_label("editor of fashion collection description", wikibase_api_url),
                    "date of fashion collection": get_property_id_by_label("date of fashion collection", wikibase_api_url),
                    "fashion show category": get_property_id_by_label("fashion show category", wikibase_api_url),
                    "fashion house X fashion collection": get_property_id_by_label("fashion house X fashion collection", wikibase_api_url),
                    "designer of collection": get_property_id_by_label("designer of collection", wikibase_api_url)}



classes_wikibase = {"fashion designer": get_entity_id_by_label("fashion designer", "wikibase")[0],
                        "fashion house": get_entity_id_by_label("fashion house", "wikibase")[0],
                        "business": get_entity_id_by_label("business", "wikibase")[0],
                        "academic institution": get_entity_id_by_label("academic institution", "wikibase")[0],
                        "geographic location": get_entity_id_by_label("geographic location", "wikibase")[0],
                        "fashion award": get_entity_id_by_label("fashion award","wikibase")[0],
                        "gender":get_entity_id_by_label("gender","wikibase")[0] , 
                        "occupation": get_entity_id_by_label("occupation","wikibase")[0],
                        "human": get_entity_id_by_label("human","wikibase")[0],
                        "organization": get_entity_id_by_label("organization","wikibase")[0],
                        "brand": get_entity_id_by_label("brand","wikibase")[0],
                        "lifestyle brand": get_entity_id_by_label("lifestyle brand","wikibase")[0],
                        "privately held company": get_entity_id_by_label("privately held company","wikibase")[0],
                        "fashion award": get_entity_id_by_label("fashion award", "wikibase")[0],
                        "fashion season": get_entity_id_by_label("fashion season", "wikibase")[0],
                        "fashion show category": get_entity_id_by_label("fashion show category", "wikibase")[0],
                        "fashion season collection": get_entity_id_by_label("fashion season collection", "wikibase")[0],
                        "fashion journalist": get_entity_id_by_label("fashion journalist", "wikibase")[0],
                        }# if get_entity_id_by_label("business", "wikibase") else None